// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace KartKraft
{

public enum VehicleState : sbyte
{
 Unknown = 0,
 Pits = 1,
 Outlap = 2,
 Racing = 3,
 Retired = 4,
};


}
